config/routes.rb
Rails.application.routes.draw do
  get 'messages/new'
  devise_for :farmers, controllers: {
    sessions: 'farmers/sessions',
    passwords: 'farmers/passwords',
    registrations: 'farmers/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  root to: "items#index" 
  resources :items do
    resources :purchase_items, only: [:new, :create]
  end

  resources :messages, only: [:new, :create]
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class='footer'>
  <div class='footer-contents'>
    <div class='vegetabel-details'>
      <h2 class='footer-content-head'>VegeTabelについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'VegeTabel利用規約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='vegetabel-details'>
      <h2 class='footer-content-head'>VegeTabelを見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
        <li><%= link_to '旬の野菜', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='vegetabel-details'>
      <h2 class='footer-content-head'>Vegetabelについて</h2>
      <ul>
        <li><%= link_to 'VegeTabelガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'Vegetabelロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <p>© VegeTabel</p>
</div>

app/views/shared/_header.html.erb
<header class="top-page-header">
  <div class="search-bar-contents">
    <%= link_to image_tag("title-logo.png", class:"title-logo"), "/" %>
    <form class="search-form" action="#">
    <input class="input-box" placeholder='例:トマト ナス'>
      <button class="search-button">
        <%= image_tag "search.png", class:"search-icon" %>
      </button>
    </form>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to 'カテゴリー', "#", class: "category-list" %></li>
      <li><%= link_to '旬の野菜', "#", class: "season-list" %></li>
    </ul>
    <ul class='lists-right'>
    <% if user_signed_in? %>
      <li><%= link_to current_user.nickname, "#", class: "user-nickname" %></li> 
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li> 
    <% elsif farmer_signed_in? %> 
      <li><%= link_to current_farmer.representative, "#", class: "farmer-name" %></li> 
      <li><%= link_to 'ログアウト', destroy_farmer_session_path, method: :delete, class: "logout" %></li>
    <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <li><%= link_to '生産者ログイン', new_farmer_session_path, class: "f-login" %></li>
      <li><%= link_to '生産者登録', new_farmer_registration_path, class: "f-sign-up" %></li>
    <% end %>
    </ul>
  </div>
</header>