config/routes.rb
Rails.application.routes.draw do
  get 'messages/new'
  devise_for :farmers, controllers: {
    sessions: 'farmers/sessions',
    passwords: 'farmers/passwords',
    registrations: 'farmers/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  root to: "items#index" 
  resources :items do
    resources :purchase_items, only: [:new, :create]
  end

  resources :messages, only: [:new, :create]
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :farmer
  has_one :purchase_item
  has_one_attached :image
  
  extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to :prefecture
    belongs_to :category
    belongs_to :delivery
    belongs_to :shipping

  with_options numericality: { other_than: 1 } do
    validates :prefecture_id, numericality: { less_than_or_equal_to: 48 }
    validates :category_id, numericality: { less_than_or_equal_to: 6 }
    validates :delivery_id, numericality: { less_than_or_equal_to: 3 }
    validates :shipping_id, numericality: { less_than_or_equal_to: 4 }
  end

  with_options presence: true do
    validates :image
    validates :name
    validates :description
    validates :contents
    validates :price, numericality: { only_integer: true, less_than: 10000000 }
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_farmer!, except: [:index, :show]
  before_action :item_info, only: [:edit, :show, :update, :destroy]
  before_action :item_authenticate, only: [:edit, :update, :destroy]

  def index
    @items = Item.includes(:farmer).order('created_at DESC')
    @items_new = Item.last(5)
    @category = Category.find(2)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def show
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(params[:id])
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :description, :contents, :category_id, :prefecture_id, :delivery_id, :shipping_id, :price).merge(farmer_id: current_farmer.id)
  end

  def item_info
    @item = Item.find(params[:id])
  end

  def item_authenticate
    unless @item.farmer == current_farmer
      redirect_to root_path
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('title-logo.png' , size: '185x50'), "/" %>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @item, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="img-upload">
      <div class="weight-bold-text">
        商品画像
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>

    <div class="new-items">
      <div class="weight-bold-text">
        商品名
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"例) トウモロコシ(品種:ゴールドラッシュ)（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
        </div>
        <%= f.text_area :description, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）例）農薬、化学肥料ともに最低限の使用に留めて、自然に優しい農業を目指しています。高原で育てているため、寒暖差が激しく甘さが売りです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
      <div class="items-contents">
        <div class="weight-bold-text">
          内容量
        </div>
      <%= f.text_area :contents, class:"items-text", id:"item-cont", placeholder:"例) トウモロコシ Lサイズ10本、 トウモロコシ サイズ色々1kg（必須 40文字まで)", maxlength:"40" %>
    </div>
    
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, { include_blanc: "---" }, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          産地
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, { include_blanc: "---" }, {class:"select-box", id:"item-prefecture"}) %>
      </div>
    </div>
    
    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
        <a class="question" href="#">?</a>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          配送料の負担
        </div>
        <%= f.collection_select(:delivery_id, Delivery.all, :id, :name, { include_blanc: "---" }, {class:"select-box", id:"item-shipping-fee-status"}) %>
        <div class="weight-bold-text">
          発送までの日数
        </div>
        <%= f.collection_select(:shipping_id, Shipping.all, :id, :name, { include_blanc: "---" }, {class:"select-box", id:"item-scheduled-delivery"}) %>
      </div>
    </div>
  
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥1〜9,999,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (5%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
        </div>
        </span>
      </div>
    </div>
    
    <div class="sell-btn-contents">
      <%= f.submit "編集する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">ベジタベル利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <p class="inc">
      ©︎VegeTabel,Inc.
    </p>
  </footer>
</div>

app/views/items/index.html.erb
<%= render "shared/header" %>

<div class="top_page_image">
  <%= image_tag "top-page-image.jpg", class: "top-page-image" %>
    <ul>
      <li>野菜を育てる喜び</li>
      <li>野菜を食べる喜びをあなたに</li>
      <li>趣味の家庭菜園からプロの農家まで誰でも出品できる</li>
    </ul>
</div>

<div class="new-content">
  <h1>新着農作物</h1>
  <%= image_tag("second-logo.png", size: "50x50", class:"second-logo") %>
</div>

<div class="main_content slide-paused" ontouchstart="">
  <% @items_new.each do |item| %>
    <ul class="slideshow">
      <li class="list content-hover">
        <%= link_to item_path(item.id) do %>
        <div class='item-img-content'>
          <%= image_tag item.image, class: "item-img" %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= item.name %>
          </h3>
          <div class='item-price'>
            <span><%= item.price %>円<br><%= item.delivery.name %></span>
          </div>
        </div>
        <% end %>
      </li>
    </ul>
  <% end %>
  <% @items_new.each do |item| %>
    <ul class="slideshow">
      <li class="list content-hover">
        <%= link_to item_path(item.id) do %>
        <div class='item-img-content'>
          <%= image_tag item.image, class: "item-img" %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= item.name %>
          </h3>
          <div class='item-price'>
            <span><%= item.price %>円<br><%= item.delivery.name %></span>
          </div>
        </div>
        <% end %>
      </li>
    </ul>
  <% end %>
  <% @items_new.each do |item| %>
    <ul class="slideshow">
      <li class="list content-hover">
        <%= link_to item_path(item.id) do %>
        <div class='item-img-content'>
          <%= image_tag item.image, class: "item-img" %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= item.name %>
          </h3>
          <div class='item-price'>
            <span><%= item.price %>円<br><%= item.delivery.name %></span>
          </div>
        </div>
        <% end %>
      </li>
    </ul>
  <% end %>
</div>

<div class="new-content">
  <h1><%= @category.name %></h1>
  <%= image_tag("second-logo.png", size: "50x50", class: "second-logo", id: "category-btn") %>
</div>

<div class="main_content slide-paused" ontouchstart="">
  <% @items.each do |item| %>
    <ul class="slideshow">
      <li class="list content-hover">
      <% if item.category.id == 2 %>
        <%= link_to item_path(item.id) do %>
        <div class='item-img-content'>
          <%= image_tag item.image, class: "item-img" %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= item.name %>
          </h3>
          <div class='item-price'>
            <span><%= item.price %>円<br><%= item.delivery.name %></span>
          </div>
        </div>
        <% end %>
      <% end %>
      </li>
    </ul>
  <% end %>
  <% @items.each do |item| %>
    <ul class="slideshow">
      <li class="list content-hover">
      <% if item.category.id == 2 %>
        <%= link_to item_path(item.id) do %>
        <div class='item-img-content'>
          <%= image_tag item.image, class: "item-img" %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= item.name %>
          </h3>
          <div class='item-price'>
            <span><%= item.price %>円<br><%= item.delivery.name %></span>
          </div>
        </div>
        <% end %>
      <% end %>
      </li>
    </ul>
  <% end %>
  <% @items.each do |item| %>
    <ul class="slideshow">
      <li class="list content-hover">
      <% if item.category.id == 2 %>
        <%= link_to item_path(item.id) do %>
        <div class='item-img-content'>
          <%= image_tag item.image, class: "item-img" %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= item.name %>
          </h3>
          <div class='item-price'>
            <span><%= item.price %>円<br><%= item.delivery.name %></span>
          </div>
        </div>
        <% end %>
      <% end %>
      </li>
    </ul>
  <% end %>
</div>

<%= link_to(new_item_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>出品する</span>
  <%= image_tag 'icon_carrots.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>

<%= render "shared/footer" %>

app/views/items/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('title-logo.png' , size: '185x50'), "/" %>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @item, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="img-upload">
      <div class="weight-bold-text">
        <label for="item-image" class="form-text">商品画像</label>
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
   
    <div class="new-items">
      <div class="weight-bold-text">
        <label for="item-name" class="form-text">商品名</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"例) トウモロコシ(品種:ゴールドラッシュ)（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          <label for="item-description" class="form-text">商品の説明</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :description, class:"items-text", id:"item-description", placeholder:"商品の説明（必須 1,000文字まで）例）農薬、化学肥料ともに最低限の使用に留めて、自然に優しい農業を目指しています。高原で育てているため、寒暖差が激しく甘さが売りです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
      <div class="items-contents">
        <div class="weight-bold-text">
          <label for="item-cont" class="form-text">内容量</label>
          <span class="indispensable">必須</span>
        </div>
      <%= f.text_area :contents, class:"items-text", id:"item-cont", placeholder:"例) トウモロコシ Lサイズ10本、 トウモロコシ サイズ色々1kg（必須 40文字まで)", maxlength:"40" %>
    </div>
    
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          <label for="item-category" class="form-text">カテゴリー</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, { include_blanc: "---" }, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          <label for="item-prefecture" class="form-text">産地</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, { include_blanc: "---" }, {class:"select-box", id:"item-prefecture"}) %>
      </div>
    </div>
    
    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>配送について</span>
        <a class="question" href="#">?</a>
      </div>
      <div class="form">
        <div class="weight-bold-text">
          <label for="item-delivery" class="form-text">配送料の負担</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:delivery_id, Delivery.all, :id, :name, { include_blanc: "---" }, {class:"select-box", id:"item-delivery"}) %>
        <div class="weight-bold-text">
          <label for="item-shipping" class="form-text">発送までの日数</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:shipping_id, Shipping.all, :id, :name, { include_blanc: "---" }, {class:"select-box", id:"item-shipping"}) %>
      </div>
    </div>
    
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <label for="item-price" class="form-text">価格</label>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (5%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
        </div>
        </span>
      </div>
    </div>
    
    <div class="sell-btn-contents">
      <%= f.submit "出品する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">ベジタベル利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('title-logo.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎VegeTabel,Inc.
    </p>
  </footer>
</div>

app/views/items/show.html.erb
<%= render "shared/header" %>

<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @item.name %>
    </h2>
    <div class="item-img-content">
      <%= image_tag @item.image, class:"item-box-img" %>
    </div>
    <div class="item-price-box">
      <span class="item-price">
        <%= "¥#{@item.price}" %>
      </span>
      <span class="item-postage">
        <%= @item.delivery.name %>
      </span>
    </div>

  <% if farmer_signed_in? %>
    <% if current_farmer.id == @item.farmer_id %>
        <%= link_to "商品の編集", edit_item_path, method: :get, class: "item-red-btn" %>
        <p class="or-text">or</p>
        <%= link_to "削除", item_path, method: :delete, class:"item-destroy" %>
    <% end %>
  <% end %>

  <% if user_signed_in? %>
    <%= link_to "購入", new_item_purchase_item_path(@item), class:"item-red-btn"%>
  <% end %>

    <div class="item-explain-box">
      <span><%= @item.description %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value"><%= @item.farmer.name %></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @item.category.name %></td>
        </tr>
        <tr>
          <th class="detail-item">配送料の負担</th>
          <td class="detail-value"><%= @item.delivery.name %></td>
        </tr>
        <tr>
          <th class="detail-item">生産地</th>
          <td class="detail-value"><%= @item.prefecture.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送日の目安</th>
          <td class="detail-value"><%= @item.shipping.name %></td>
        </tr>
      </tbody>
    </table>
  <%=link_to 'もどる', root_path, class:"back-btn" %>
</div>

<%= render "shared/footer" %>